[package]
name = "line_index"
author = "Luna Razzaghipour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-size = "1.1"
